### Variables

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDg1YmQ2Yi1hYjQ3LTQxNTgtYmUzYi1lODNkNjQ1MWNkMTYiLCJ1c2VyRW1haWwiOiJldUBlbWFpbC5jb20iLCJpYXQiOjE3MjcxODAwMTYsImV4cCI6MTcyNzE4MDA1MX0.oQaqoTOkRun8TZnZYL56CrWXSCmj9bcZ0gQ5DcjZwPI
@refresh_token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDg1YmQ2Yi1hYjQ3LTQxNTgtYmUzYi1lODNkNjQ1MWNkMTYiLCJ1c2VyRW1haWwiOiJldUBlbWFpbC5jb20iLCJpYXQiOjE3MjcxNzk5MjYsImV4cCI6MTcyNzc4NDcyNn0.eXZNWiWNedSVIxLnkGXfigciGlMrhRK8u1X_r-x6zS8

###

POST http://localhost:3000/auth/signin HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "email": "eu@email.com",
    "password": "123"
}

###

POST http://localhost:3000/auth/signup HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "email": "eu@email.com",
    "first_name": "eu",
    "last_name": "é",
    "password": "123"
}

###

POST http://localhost:3000/user/create HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "email": "eu@email.com",
    "first_name": "eu",
    "last_name": "er",
    "password": "123"
}

###

POST http://localhost:3000/user/create HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "email": "tu@email.com",
    "first_name": "tu",
    "last_name": "ta",
    "password": "12345"
}

###

PUT http://localhost:3000/user/update HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "email": "eu@email.com",
    "first_name": "c",
    "last_name": "er",
    "password": "123"
}

###

PUT http://localhost:3000/user/update-me HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "email": "vc@email.com",
    "first_name": "cc",
    "last_name": "er",
    "password": "123"
}

###

DELETE http://localhost:3000/user/delete/eu@email.com
Authorization: Bearer {{access_token}}
###

DELETE http://localhost:3000/user/delete-all
Authorization: Bearer {{access_token}}
###

GET http://localhost:3000/user/find-one/eu@email.com
Authorization: Bearer {{access_token}}
###

GET http://localhost:3000/user/find-all
Authorization: Bearer {{access_token}}

###

GET http://localhost:3000/auth/refresh-token
Content-Type: application/json
Authorization: Refresh {{refresh_token}}

{
    "email": "eu@email.com"
}