import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "My project",
    default: 'Next.js',
    template: "%s Root Template"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
